name = "terrell-worker"
main = "workers/worker.js"
compatibility_date = "2026-07-03"
type = "javascript"

# Fill your account_id before publishing

account_id = "e02ea8e0b7fe319f04e2505df1138d4c"

[[d1_databases]]
binding = "TERRELL_D1"
database_name = "617678ce-59e6-4742-a41c-469e9096f4f6"

[[r2_buckets]]
binding = "TERRELL_MEDIA"
bucket_name = "terrell-media"

# You can add routes or environments here; by default this publishes a worker to
# <name>.workers.dev when you run `wrangler publish` (account_id must be set).
